name: Build nightly release

permissions:
  contents: write

on:
  schedule:
    - cron: "0 7 * * *"
  push:
    tags:
      - "nightly"
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get current date
        id: date
        run: |
          $NOW=& Get-Date -format yyyy-MM-dd
          echo "NOW=$NOW" >> $env:GITHUB_ENV

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false
          repository: zed-industries/zed

      - name: Setup build tools
        run: |
          rustc --version
          cargo --version
          rustup target add wasm32-wasi

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build nightly
        run: cargo build --release --locked --package zed

      - name: Create nightly release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "nightly-${{ $env:NOW }}" \
            --title "Nightly ${{ $env:NOW }}" \
            --prerelease \
            target\release\zed.exe
