name: Build nightly release

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * *"
  push:
    tags:
      - "nightly"

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false
          repository: zed-industries/zed

      - name: Get current date
        id: vars
        run: |
          $NOW = (Get-Date -format yyyy.MM.dd)
          echo "NOW: ${NOW}"
          Write-Output "now=${NOW}" >> $Env:GITHUB_OUTPUT
          $HASH = (git rev-parse HEAD).Substring(0,9)
          echo "HASH: ${HASH}"
          Write-Output "hash=${HASH}" >> $Env:GITHUB_OUTPUT

      - name: Setup build tools
        run: |
          rustc --version
          cargo --version
          rustup target add wasm32-wasi

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build nightly
        run: cargo build --release --locked --package zed

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zed-editor
          path: target\release\zed.exe

      - name: Create nightly release
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ steps.vars.outputs.now }}-${{ steps.vars.outputs.hash }}" --title "${{ steps.vars.outputs.now }}-${{ steps.vars.outputs.hash }}" --notes "Nightly build" --repo geerteltink/zed-windows --latest target\release\zed.exe
