name: Sync Upstream

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: ClanEver/zed
        fetch-depth: 0  # 获取所有历史记录
        
    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        
    - name: Add Upstream Remote
      run: git remote add upstream https://github.com/zed-industries/zed.git
      
    - name: Fetch Upstream Main
      run: git fetch upstream main  # 只获取 main 分支
      
    - name: Merge Upstream
      run: |
        git checkout main
        git merge upstream/main
        
    - name: Push Changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
