name: Sync Upstream

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        clean: true
        repository: ClanEver/zed
        ref: main
        fetch-depth: 0
        token: ${{ secrets.SYNC_TOKEN }}

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Fetch and Merge
      run: |
        git checkout main
        git pull origin main
        git remote add upstream https://github.com/zed-industries/zed.git
        git fetch upstream main
        git merge upstream/main
        git push origin main
