name: Sync Upstream

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout zed repository
      uses: actions/checkout@v3
      with:
        repository: ClanEver/zed
        token: ${{ secrets.PAT }}
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Fetch and Merge
      run: |
        git checkout main
        git pull origin main
        git remote add upstream https://github.com/zed-industries/zed.git
        git fetch upstream main
        git merge upstream/main
        git push origin main
