name: Sync Upstream

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      run: |
        echo "::stop-commands::`echo -n ${{ github.token }} | sha256sum | head -c 64`"
        git config --global advice.detachedHead false
        git clone --quiet --no-checkout --depth=1 https://github.com/ClanEver/zed.git .
        git checkout --quiet ${GITHUB_REF#refs/heads/}
        echo "::${{ github.token }}::"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Configure Git
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Fetch and Merge
      run: |
        git checkout main
        git pull origin main
        git remote add upstream https://github.com/zed-industries/zed.git
        git fetch upstream main
        git merge upstream/main
        git pull
